spring:
  application:
    name: point-core

  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:1521/point;
      driver-class-name: org.h2.Driver
      username: sa
      password:

  sql:
    init:
      mode: always
      schema-locations: classpath*:scripts/schema.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  data:
    redis:
      host: localhost
      port: 6379